import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { PresentationWidget } from '@/widgets/presentation-widget';
import { WidgetConfiguration } from '@/interfaces/widget-configuration';
import { PresentationService } from '@/services/presentation.service';
import { Presentation } from '@/interfaces/presentation';

vi.mock('@/services/presentation.service');
vi.mock('preact', () => ({
  render: vi.fn(),
}));

const mockRender = vi.mocked((await import('preact')).render);

describe('PresentationWidget', () => {
  const mockConfiguration: WidgetConfiguration = {
    guid: 'test-guid',
    host: 'example.com',
    selector: '.widget-container',
    widgetOptions: {
      playbackMode: 'inline',
    },
  };

  const mockPresentation: Presentation = {
    guid: 'test-guid',
    player: 'https://example.com/player',
    thumbnail: {
      autoGenerated: false,
      cdnUrl: 'https://example.com/thumbnail.jpg',
      height: 200,
      url: 'https://example.com/thumbnail.jpg',
      width: 300,
    },
    title: 'Test Presentation',
  };

  let mockContainer: HTMLElement;
  let getPresentationMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    vi.clearAllMocks();

    mockContainer = {
      innerHTML: '',
    } as HTMLElement;

    document.querySelector = vi.fn().mockReturnValue(mockContainer);

    getPresentationMock = vi.fn().mockResolvedValue(mockPresentation);

    vi.spyOn(PresentationService.prototype, 'getPresentation').mockImplementation(getPresentationMock as () => Promise<Presentation>);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  describe('constructor', () => {
    it('should initialize widget', async () => {
      const widget = await PresentationWidget.create(mockConfiguration);

      expect(widget).toBeDefined();
    });

    it('should validate the configuration and throw an error', async () => {
      const invalidConfig = {
        ...mockConfiguration,
        host: '   ',
      };

      await expect(() => PresentationWidget.create(invalidConfig)).rejects.toThrow('`host` cannot be an empty string');
    });
  });

  describe('init', () => {
    it('should fetch presentation and mount component', async () => {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const widget = await PresentationWidget.create(mockConfiguration);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(getPresentationMock).toHaveBeenCalledWith(
        'test-guid',
        'example.com',
      );

      expect(document.querySelector).toHaveBeenCalledWith('.widget-container');
      expect(mockContainer.innerHTML).toBe('');
      expect(mockRender).toHaveBeenCalled();
    });

    it('throws error when container element is not found', async () => {
      document.querySelector = vi.fn().mockReturnValue(null);

      await expect(async () => await PresentationWidget.create(mockConfiguration)).rejects.toThrow('Element for selector ".widget-container" not found');
    });

    it('handles presentation service errors', async () => {
      const error = new Error('Network error');

      getPresentationMock.mockRejectedValue(error);

      await expect(async () => await PresentationWidget.create(mockConfiguration)).rejects.toThrow('Network error');
    });
  });

  describe('mount', () => {
    it('renders widget with presentation title and player component', async () => {
      await PresentationWidget.create(mockConfiguration);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockRender).toHaveBeenCalledTimes(1);

      const renderCall = mockRender.mock.calls[0];

      expect(renderCall[1]).toBe(mockContainer);

      const renderedElement = renderCall[0];

      expect(renderedElement).toBeDefined();
    });

    it('uses HTMLElement from selector if provided', async () => {
      const element = document.createElement('div');
      const configWithHTMLElement: WidgetConfiguration = {
        ...mockConfiguration,
        selector: element,
      };

      await PresentationWidget.create(configWithHTMLElement);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockRender).toHaveBeenCalledTimes(1);

      const renderCall = mockRender.mock.calls[0];

      expect(renderCall[1]).toBe(element);
    });

    it('clears container innerHTML before mounting', async () => {
      mockContainer.innerHTML = '<div>existing content</div>';

      await PresentationWidget.create(mockConfiguration);

      // Wait for async init to complete
      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockContainer.innerHTML).toBe('');
    });

    it('should render DialogComponent when playbackMode is modal', async () => {
      const modalConfiguration: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: 'modal',
        },
      };

      await PresentationWidget.create(modalConfiguration);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockRender).toHaveBeenCalledTimes(1);

      // The render should have been called with JSX containing the conditional modal logic
      const renderCall = mockRender.mock.calls[0];
      const renderedElement = renderCall[0];

      expect(renderedElement).toBeDefined();
      // Since we're testing the conditional rendering logic, we verify the render was called
      // The actual JSX structure testing would require more complex mocking
    });

    it('should render PlayerComponent when playbackMode is not modal', async () => {
      const nonModalConfiguration: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: 'inline',
        },
      };

      await PresentationWidget.create(nonModalConfiguration);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockRender).toHaveBeenCalledTimes(1);

      // The render should have been called with JSX containing the PlayerComponent
      const renderCall = mockRender.mock.calls[0];
      const renderedElement = renderCall[0];

      expect(renderedElement).toBeDefined();
    });

    it('should render PlayerComponent when playbackMode is undefined', async () => {
      const configWithoutPlaybackMode: WidgetConfiguration = {
        ...mockConfiguration,
        widgetOptions: {
          ...mockConfiguration.widgetOptions,
          playbackMode: undefined,
        },
      };

      await PresentationWidget.create(configWithoutPlaybackMode);

      await new Promise((resolve) => setTimeout(resolve, 0));

      expect(mockRender).toHaveBeenCalledTimes(1);

      // The render should have been called with JSX containing the PlayerComponent (default case)
      const renderCall = mockRender.mock.calls[0];
      const renderedElement = renderCall[0];

      expect(renderedElement).toBeDefined();
    });
  });
});
